### ISSUE TITLE
No such file or directory: './animal_data/clean_data/keypoints_18.json'

### ISSUE THREAD

**Issue by Kana-alt** [chaneyddtt/UDA-Animal-Pose#2]
How can I solve the following error?

python synthetic_animal_sp_all.py
Traceback (most recent call last):
  File "synthetic_animal_sp_all.py", line 255, in <module>
    generate_data_file()
  File "synthetic_animal_sp_all.py", line 64, in generate_data_file
    with open('{}/clean_data/keypoints_18.json'.format(data_dir), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './animal_data/clean_data/keypoints_18.json'

**Comment by chaneyddtt** [comment]
Hi @Kana-alt,
you can download or generate the keypoints data according to the data preprocess step.

**Comment by Kana-alt** [comment]
I tried to generate keypoint data by running "synthetic_animal_sp_all.py".

However, an error occurred.

**Comment by chaneyddtt** [comment]
Can you create a folder 'clean_data' under the 'animal_data' directory, and then run the code again? Please let me know if the error still occurs.

**Comment by Kana-alt** [comment]
Thank you!
I've solved the problem.

**Comment by Kana-alt** [comment]
I'm sorry for asking so many questions.

I'm trying to get to the "train" stage.

I am trying to "CUDA_VISIBLE_DEVICES=0 python train/train_refinenet.py --arch pose_resnet_refine --checkpoint . /checkpoint/all/syn_refinenet --animal all --solver adam --dataset synthetic_animal_sp_all --dataset_real real_animal_all --train_on_all_ cat" was successfully executed.


Then run "python train/train_refinenet_mt.py --arch pose_resnet_refine_mt_multida --checkpoint . /checkpoint/all/syn2real_refinenet_mt --dual_branch --mixup_dual --dataset_real_crop real_animal_crop_all --occlusion_aug --pretrained . /checkpoint/all/syn_refinenet_re/model_best.pth.tar --animal all --dataset_real real_animal_all --dataset synthetic_animal_sp_all --train When I ran "_on_all_cat --generate_pseudol", the following error occurred.

Please let me know the solution.


Epoch: 1 | LR: 0.000250 | Trg_weight: 15.000000 | C2rcons_weight: 0.606415

==> real_animal_all
Animal:horse, number of frames:13545, train: 8380, valid: 1772
Total number of frames:13545, train: 8380, valid 1772
load from mean file: ./data/synthetic_animal/all_combineds5r5_texture/mean.pth.tar
  Real animal  mean: 0.3999, 0.3909, 0.3871
  Real animal  std:  0.2589, 0.2431, 0.2291
Traceback (most recent call last):
  File "train/train_refinenet_mt.py", line 547, in <module>
    main(parser.parse_args())
  File "train/train_refinenet_mt.py", line 182, in main
    score_map, generated_kpts = prediction_check(previous_img, previous_kpts, trg_img[i], model, real_dataset_train, device, num_transform=5)
  File "C:\Users\kana\Desktop\Synthetic-Animals2\UDA-Animal-Pose-main\train\..\CCSSL\scripts\consistency.py", line 59, in prediction_check
    M = cv2.getRotationMatrix2D((32,32),-rot,1)
TypeError: Argument 'angle' can not be treated as a double
